gems:
  production:
    - sinatra
    - thin
    - rake

  test:
    - cucumber
    - capybara
    - guard-cucumber

  test_require_false:
    - cucumber-api-steps

files:
  Gemfile:
  Rakefile:
  Procfile:
  config.ru:
  features/first.feature:
    outpath: first/path
  features/support/env.rb:
  lib/app.rb:
    outpath: app/path
  .ruby-version:
