gems:
  production:
    - sinatra
    - thin
    - rake

  test:
    - cucumber
    - capybara
    - guard-cucumber

  test_require_false:
    - cucumber-api-steps

files:
  Gemfile:
  Rakefile:
  Procfile:
  .ruby-version:
  config.ru:
  # the template has this name
  features/first.feature:
    # but the output file substitutes it like this, where wormname is an attribute
    # on the Generator object
    outpath: first/wormname
  features/support/env.rb:
  lib/app.rb:
    outpath: app/wormname
